require_relative "types/ruby_type"
require_relative "types/array_type"
require_relative "types/class_type"
require_relative "types/primitive_type"
require_relative "types/union_type"
require_relative "types/struct_type"
require_relative "types/array_command_type"

require_relative "inference/object_tracer"
require_relative "inference/ruby_extension"
require_relative "inference/symbol_table"
require_relative "inference/ast_inference"
require_relative "inference/input_inference"
require_relative "inference/command_inference"
